
Public Class msbdata
    Private fieldNames As List(Of String) = New List(Of String)
    Private fieldtypes As List(Of String) = New List(Of String)
    Private fieldBackColor As List(Of Color) = New List(Of Color)

    Private nameIdx As Integer
    Public Sub add(ByVal name As String, ByVal type As String, backColor As Color)
        fieldNames.Add(name)
        fieldtypes.Add(type)
        fieldBackColor.Add(backColor)
    End Sub
    Public Function retrieveName(ByVal i As Integer) As String
        Return fieldNames(i)
    End Function
    Public Function retrieveType(ByVal i As Integer) As String
        Return fieldtypes(i)
    End Function
    Public Function retrieveBackColor(ByVal i As Integer) As Color
        Return fieldBackColor(i)
    End Function
    Public Function fieldCount() As Integer
        Return fieldNames.Count
    End Function
    Public Function getNameIndex() As Integer
        Return nameIdx
    End Function
    Public Sub setNameIndex(ByVal idx As Integer)
        nameIdx = idx
    End Sub
    Public Function getFieldIndex(ByVal name As String) As Integer
        Return fieldNames.IndexOf(name)
    End Function

    Public Shared Function generate(ByVal name As String)
        Dim layout = New msbdata

        With layout
            If name = "models" Then
                .add("Name Offset", "i32", Color.White)
                .add("Type", "i32", Color.White)
                .add("Index", "i32", Color.White)
                .add("Sib Offset", "i32", Color.White)
                .add("x10", "i32", Color.LightGray)
                .add("x14", "i32", Color.LightGray)
                .add("x18", "i32", Color.LightGray)
                .add("x1C", "i32", Color.LightGray)
                .setNameIndex(.fieldCount)
                .add("Name", "string", Color.White)
                .add("Sibpath", "string", Color.White)
            ElseIf name = "points0" Then
                .add("Name Offset", "i32", Color.White)
                .add("x04", "i32", Color.LightGray)
                .add("index", "i32", Color.White)
                .add("Type", "i32", Color.White)
                .add("X pos", "f32", Color.White)
                .add("Y pos", "f32", Color.White)
                .add("Z pos", "f32", Color.White)
                .add("Rot X", "f32", Color.White)
                .add("Rot Y", "f32", Color.White)
                .add("Rot Z", "f32", Color.White)
                .add("x28", "i32", Color.LightGray)
                .add("x2c", "i32", Color.LightGray)
                .add("x30", "i32", Color.LightGray)
                .add("x34", "i32", Color.LightGray)
                .setNameIndex(.fieldCount)
                .add("Name", "string", Color.White)
                .add("p+0x00", "i32", Color.LightGray)
                .add("p+0x04", "i32", Color.LightGray)
                .add("EventEntityID", "i32", Color.White)
            ElseIf name = "points2" Then
                .add("Name Offset", "i32", Color.White)
                .add("x04", "i32", Color.LightGray)
                .add("index", "i32", Color.White)
                .add("Type", "i32", Color.White)
                .add("X pos", "f32", Color.White)
                .add("Y pos", "f32", Color.White)
                .add("Z pos", "f32", Color.White)
                .add("Rot X", "f32", Color.White)
                .add("Rot Y", "f32", Color.White)
                .add("Rot Z", "f32", Color.White)
                .add("x28", "i32", Color.LightGray)
                .add("x2c", "i32", Color.LightGray)
                .add("x30", "i32", Color.LightGray)
                .add("x34", "i32", Color.LightGray)
                .setNameIndex(.fieldCount)
                .add("Name", "string", Color.White)
                .add("p+0x00", "i32", Color.LightGray)
                .add("p+0x04", "i32", Color.LightGray)
                .add("p+0x08", "f32", Color.LightGray)
                .add("EventEntityID", "i32", Color.White)
            ElseIf name = "points3" Then
                .add("Name Offset", "i32", Color.White)
                .add("x04", "i32", Color.LightGray)
                .add("index", "i32", Color.White)
                .add("Type", "i32", Color.White)
                .add("X pos", "f32", Color.White)
                .add("Y pos", "f32", Color.White)
                .add("Z pos", "f32", Color.White)
                .add("Rot X", "f32", Color.White)
                .add("Rot Y", "f32", Color.White)
                .add("Rot Z", "f32", Color.White)
                .add("x28", "i32", Color.LightGray)
                .add("x2c", "i32", Color.LightGray)
                .add("x30", "i32", Color.LightGray)
                .add("x34", "i32", Color.LightGray)
                .setNameIndex(.fieldCount)
                .add("Name", "string", Color.White)
                .add("p+0x00", "i32", Color.LightGray)
                .add("p+0x04", "i32", Color.LightGray)
                .add("p+0x08", "f32", Color.LightGray)
                .add("p+0x0C", "f32", Color.LightGray)
                .add("EventEntityID", "i32", Color.White)
            ElseIf name = "points5" Then
                .add("Name Offset", "i32", Color.White)
                .add("x04", "i32", Color.LightGray)
                .add("index", "i32", Color.White)
                .add("Type", "i32", Color.White)
                .add("X pos", "f32", Color.White)
                .add("Y pos", "f32", Color.White)
                .add("Z pos", "f32", Color.White)
                .add("Rot X", "f32", Color.White)
                .add("Rot Y", "f32", Color.White)
                .add("Rot Z", "f32", Color.White)
                .add("x28", "i32", Color.LightGray)
                .add("x2c", "i32", Color.LightGray)
                .add("x30", "i32", Color.LightGray)
                .add("x34", "i32", Color.LightGray)
                .setNameIndex(.fieldCount)
                .add("Name", "string", Color.White)
                .add("p+0x00", "i32", Color.LightGray)
                .add("p+0x04", "i32", Color.LightGray)
                .add("p+0x08", "f32", Color.LightGray)
                .add("p+0x0C", "f32", Color.LightGray)
                .add("p+0x10", "f32", Color.LightGray)
                .add("EventEntityID", "i32", Color.White)
            ElseIf name = "mapPieces0" Then
                .add("Name Offset", "i32", Color.White)
                .add("Type", "i32", Color.White)
                .add("Index", "i32", Color.White)
                .add("Model", "i32", Color.White)
                .add("Sib Offset", "i32", Color.White)
                .add("X pos", "f32", Color.White)
                .add("Y pos", "f32", Color.White)
                .add("Z pos", "f32", Color.White)
                .add("Rot X", "f32", Color.White)
                .add("Rot Y", "f32", Color.White)
                .add("Rot Z", "f32", Color.White)
                .add("Scale X", "f32", Color.White)
                .add("Scale Y", "f32", Color.White)
                .add("Scale Z", "f32", Color.White)
                .add("x38", "i32", Color.LightGray)
                .add("DrawGroup1", "i32", Color.White)
                .add("DrawGroup2", "i32", Color.White)
                .add("DrawGroup3", "i32", Color.White)
                .add("DrawGroup4", "i32", Color.White)
                .add("x4c", "i32", Color.LightGray)
                .add("x50", "i32", Color.LightGray)
                .add("x54", "i32", Color.LightGray)
                .add("x58", "i32", Color.LightGray)
                .add("x5C", "i32", Color.LightGray)
                .add("x60", "i32", Color.LightGray)
                .setNameIndex(.fieldCount)
                .add("Name", "string", Color.White)
                .add("Sibpath", "string", Color.White)
                .add("EventEntityID", "i32", Color.White)
                .add("LightId", "i8", Color.White)
                .add("FogId", "i8", Color.White)
                .add("ScatId", "i8", Color.White)
                .add("p+x07", "i8", Color.LightGray)
                .add("p+x08", "i8", Color.LightGray)
                .add("p+x09", "i8", Color.LightGray)
                .add("p+x0A", "i8", Color.LightGray)
                .add("p+x0B", "i8", Color.LightGray)
                .add("p+x0C", "i32", Color.LightGray)
                .add("p+x10", "i32", Color.LightGray)
                .add("p+x14", "i32", Color.LightGray)
                .add("p+x18", "i32", Color.LightGray)
                .add("p+x1C", "i32", Color.LightGray)
            ElseIf name = "objects1" Then
                .add("Name Offset", "i32", Color.White)
                .add("Type", "i32", Color.White)
                .add("Index", "i32", Color.White)
                .add("Model", "i32", Color.White)
                .add("Sib Offset", "i32", Color.White)
                .add("X pos", "f32", Color.White)
                .add("Y pos", "f32", Color.White)
                .add("Z pos", "f32", Color.White)
                .add("Rot X", "f32", Color.White)
                .add("Rot Y", "f32", Color.White)
                .add("Rot Z", "f32", Color.White)
                .add("Scale X", "f32", Color.White)
                .add("Scale Y", "f32", Color.White)
                .add("Scale Z", "f32", Color.White)
                .add("x38", "i32", Color.LightGray)
                .add("x3C", "i32", Color.LightGray)
                .add("x40", "i32", Color.LightGray)
                .add("x44", "i32", Color.LightGray)
                .add("x48", "i32", Color.LightGray)
                .add("x4C", "i32", Color.LightGray)
                .add("x50", "i32", Color.LightGray)
                .add("x54", "i32", Color.LightGray)
                .add("x58", "i32", Color.LightGray)
                .add("x5C", "i32", Color.LightGray)
                .add("x60", "i32", Color.LightGray)
                .setNameIndex(.fieldCount)
                .add("Name", "string", Color.White)
                .add("Sibpath", "string", Color.White)
                .add("EventEntityID", "i32", Color.White)
                .add("LightId", "i8", Color.White)
                .add("FogId", "i8", Color.White)
                .add("ScatId", "i8", Color.White)
                .add("p+x07", "i8", Color.LightGray)
                .add("p+x08", "i32", Color.LightGray)
                .add("p+x0C", "i8", Color.LightGray)
                .add("p+x0D", "i8", Color.LightGray)
                .add("p+x0E", "i8", Color.LightGray)
                .add("p+x0F", "i8", Color.LightGray)
                .add("p+x10", "i8", Color.LightGray)
                .add("p+x11", "i8", Color.LightGray)
                .add("p+x12", "i8", Color.LightGray)
                .add("p+x13", "i8", Color.LightGray)
                .add("p+x14", "i32", Color.LightGray)
                .add("p+x18", "i32", Color.LightGray)
                .add("PhysIndex", "i32", Color.White)
                .add("p+x20", "i32", Color.LightGray)
                .add("p+x24", "i32", Color.LightGray)
                .add("p+x28", "i32", Color.LightGray)
                .add("p+x2C", "i32", Color.LightGray)
            ElseIf name = "creatures2" Then
                .add("Name Offset", "i32", Color.White)
                .add("Type", "i32", Color.White)
                .add("Index", "i32", Color.White)
                .add("Model", "i32", Color.White)
                .add("Sib Offset", "i32", Color.White)
                .add("X pos", "f32", Color.White)
                .add("Y pos", "f32", Color.White)
                .add("Z pos", "f32", Color.White)
                .add("Rot X", "f32", Color.White)
                .add("Rot Y", "f32", Color.White)
                .add("Rot Z", "f32", Color.White)
                .add("Scale X", "f32", Color.White)
                .add("Scale Y", "f32", Color.White)
                .add("Scale Z", "f32", Color.White)
                .add("x38", "i32", Color.LightGray)
                .add("x3C", "i32", Color.LightGray)
                .add("x40", "i32", Color.LightGray)
                .add("x44", "i32", Color.LightGray)
                .add("x48", "i32", Color.LightGray)
                .add("x4C", "i32", Color.LightGray)
                .add("x50", "i32", Color.LightGray)
                .add("x54", "i32", Color.LightGray)
                .add("x58", "i32", Color.LightGray)
                .add("x5C", "i32", Color.LightGray)
                .add("x60", "i32", Color.LightGray)
                .setNameIndex(.fieldCount)
                .add("Name", "string", Color.White)
                .add("Sibpath", "string", Color.White)
                .add("EventEntityID", "i32", Color.White)
                .add("LightId", "i8", Color.White)
                .add("FogId", "i8", Color.White)
                .add("ScatId", "i8", Color.White)
                .add("p+x07", "i8", Color.LightGray)
                .add("p+x08", "i32", Color.LightGray)
                .add("p+x0C", "i32", Color.LightGray)
                .add("p+x10", "i32", Color.LightGray)
                .add("p+x14", "i32", Color.LightGray)
                .add("p+x18", "i32", Color.LightGray)
                .add("p+x1C", "i32", Color.LightGray)
                .add("AI", "i32", Color.White)
                .add("NPCParam", "i32", Color.White)
                .add("TalkID", "i32", Color.White)
                .add("p+x2C", "i32", Color.LightGray)
                .add("ChrInitParam", "i32", Color.White)
                .add("PhysIndex", "i32", Color.White)
                .add("p+x38", "i32", Color.LightGray)
                .add("p+x3C", "i32", Color.LightGray)
                .add("p+x40", "i32", Color.LightGray)
                .add("p+x44", "i32", Color.LightGray)
                .add("p+x48", "i32", Color.LightGray)
                .add("p+x4C", "i32", Color.LightGray)
                .add("AnimID", "i32", Color.White)
                .add("p+x54", "i32", Color.LightGray)
            ElseIf name = "creatures4" Then
                .add("Name Offset", "i32", Color.White)
                .add("Type", "i32", Color.White)
                .add("Index", "i32", Color.White)
                .add("Model", "i32", Color.White)
                .add("Sib Offset", "i32", Color.White)
                .add("X pos", "f32", Color.White)
                .add("Y pos", "f32", Color.White)
                .add("Z pos", "f32", Color.White)
                .add("Rot X", "f32", Color.White)
                .add("Rot Y", "f32", Color.White)
                .add("Rot Z", "f32", Color.White)
                .add("Scale X", "f32", Color.White)
                .add("Scale Y", "f32", Color.White)
                .add("Scale Z", "f32", Color.White)
                .add("x38", "i32", Color.LightGray)
                .add("x3C", "i32", Color.LightGray)
                .add("x40", "i32", Color.LightGray)
                .add("x44", "i32", Color.LightGray)
                .add("x48", "i32", Color.LightGray)
                .add("x4C", "i32", Color.LightGray)
                .add("x50", "i32", Color.LightGray)
                .add("x54", "i32", Color.LightGray)
                .add("x58", "i32", Color.LightGray)
                .add("x5C", "i32", Color.LightGray)
                .add("x60", "i32", Color.LightGray)
                .setNameIndex(.fieldCount)
                .add("Name", "string", Color.White)
                .add("Sibpath", "string", Color.White)
                .add("EventEntityID", "i32", Color.White)
                .add("LightId", "i8", Color.White)
                .add("FogId", "i8", Color.White)
                .add("ScatId", "i8", Color.White)
                .add("p+x07", "i8", Color.LightGray)
                .add("p+x08", "i32", Color.LightGray)
                .add("p+x0C", "i32", Color.LightGray)
                .add("p+x10", "i32", Color.LightGray)
                .add("p+x14", "i32", Color.LightGray)
                .add("p+x18", "i32", Color.LightGray)
                .add("p+x1C", "i32", Color.LightGray)
                .add("p+x20", "i32", Color.LightGray)
                .add("p+x24", "i32", Color.LightGray)
            ElseIf name = "collision5" Then
                .add("Name Offset", "i32", Color.White)
                .add("Type", "i32", Color.White)
                .add("Index", "i32", Color.White)
                .add("Model", "i32", Color.White)
                .add("Sib Offset", "i32", Color.White)
                .add("X pos", "f32", Color.White)
                .add("Y pos", "f32", Color.White)
                .add("Z pos", "f32", Color.White)
                .add("Rot X", "f32", Color.White)
                .add("Rot Y", "f32", Color.White)
                .add("Rot Z", "f32", Color.White)
                .add("Scale X", "f32", Color.White)
                .add("Scale Y", "f32", Color.White)
                .add("Scale Z", "f32", Color.White)
                .add("x38", "i32", Color.LightGray)
                .add("x3C", "i32", Color.LightGray)
                .add("x40", "i32", Color.LightGray)
                .add("x44", "i32", Color.LightGray)
                .add("x48", "i32", Color.LightGray)
                .add("x4C", "i32", Color.LightGray)
                .add("x50", "i32", Color.LightGray)
                .add("x54", "i32", Color.LightGray)
                .add("x58", "i32", Color.LightGray)
                .add("x5C", "i32", Color.LightGray)
                .add("x60", "i32", Color.LightGray)
                .setNameIndex(.fieldCount)
                .add("Name", "string", Color.White)
                .add("Sibpath", "string", Color.White)
                .add("EventEntityID", "i32", Color.White)
                .add("p+x04", "i8", Color.LightGray)
                .add("p+x05", "i8", Color.LightGray)
                .add("p+x06", "i8", Color.LightGray)
                .add("p+x07", "i8", Color.LightGray)
                .add("p+x08", "i8", Color.LightGray)
                .add("p+x09", "i8", Color.LightGray)
                .add("p+x0A", "i8", Color.LightGray)
                .add("p+x0B", "i8", Color.LightGray)
                .add("p+x0C", "i8", Color.LightGray)
                .add("p+x0D", "i8", Color.LightGray)
                .add("p+x0E", "i8", Color.LightGray)
                .add("p+x0F", "i8", Color.LightGray)
                .add("p+x10", "i8", Color.LightGray)
                .add("p+x11", "i8", Color.LightGray)
                .add("p+x12", "i8", Color.LightGray)
                .add("p+x13", "i8", Color.LightGray)
                .add("p+x14", "i8", Color.LightGray)
                .add("p+x15", "i8", Color.LightGray)
                .add("p+x16", "i8", Color.LightGray)
                .add("p+x17", "i8", Color.LightGray)
                .add("p+x18", "i8", Color.LightGray)
                .add("p+x19", "i8", Color.LightGray)
                .add("p+x1A", "i8", Color.LightGray)
                .add("p+x1B", "i8", Color.LightGray)
                .add("p+x1C", "i8", Color.LightGray)
                .add("p+x1D", "i8", Color.LightGray)
                .add("p+x1E", "i8", Color.LightGray)
                .add("p+x1F", "i8", Color.LightGray)
                .add("p+x20", "i32", Color.LightGray)
                .add("p+x24", "i32", Color.LightGray)
                .add("p+x28", "i32", Color.LightGray)
                .add("p+x2C", "i32", Color.LightGray)
                .add("p+x30", "i32", Color.LightGray)
                .add("p+x34", "i32", Color.LightGray)
                .add("p+x38", "i32", Color.LightGray)
                .add("p+x3C", "i16", Color.LightGray)
                .add("p+x3E", "i16", Color.LightGray)
                .add("p+x40", "i32", Color.LightGray)
                .add("p+x44", "i32", Color.LightGray)
                .add("p+x48", "i32", Color.LightGray)
                .add("p+x4C", "i32", Color.LightGray)
                .add("p+x50", "i32", Color.LightGray)
                .add("p+x54", "i16", Color.LightGray)
                .add("p+x56", "i16", Color.LightGray)
                .add("p+x58", "i32", Color.LightGray)
                .add("p+x5C", "i32", Color.LightGray)
                .add("p+x60", "i32", Color.LightGray)
                .add("p+x64", "i32", Color.LightGray)
            ElseIf name = "navimesh8" Then
                .add("Name Offset", "i32", Color.White)
                .add("Type", "i32", Color.White)
                .add("Index", "i32", Color.White)
                .add("Model", "i32", Color.White)
                .add("Sib Offset", "i32", Color.White)
                .add("X pos", "f32", Color.White)
                .add("Y pos", "f32", Color.White)
                .add("Z pos", "f32", Color.White)
                .add("Rot X", "f32", Color.White)
                .add("Rot Y", "f32", Color.White)
                .add("Rot Z", "f32", Color.White)
                .add("Scale X", "f32", Color.White)
                .add("Scale Y", "f32", Color.White)
                .add("Scale Z", "f32", Color.White)
                .add("x38", "i32", Color.LightGray)
                .add("DrawGroup1", "i32", Color.White)
                .add("DrawGroup2", "i32", Color.White)
                .add("DrawGroup3", "i32", Color.White)
                .add("DrawGroup4", "i32", Color.White)
                .add("x4c", "i32", Color.LightGray)
                .add("x50", "i32", Color.LightGray)
                .add("x54", "i32", Color.LightGray)
                .add("x58", "i32", Color.LightGray)
                .add("x5C", "i32", Color.LightGray)
                .add("x60", "i32", Color.LightGray)
                .setNameIndex(.fieldCount)
                .add("Name", "string", Color.White)
                .add("Sibpath", "string", Color.White)
                .add("EventEntityID", "i32", Color.White)
                .add("LightId", "i8", Color.White)
                .add("FogId", "i8", Color.White)
                .add("ScatId", "i8", Color.White)
                .add("p+x07", "i8", Color.LightGray)
                .add("p+x08", "i8", Color.LightGray)
                .add("p+x09", "i8", Color.LightGray)
                .add("p+x0A", "i8", Color.LightGray)
                .add("p+x0B", "i8", Color.LightGray)
                .add("p+x0C", "i32", Color.LightGray)
                .add("p+x10", "i32", Color.LightGray)
                .add("p+x14", "i32", Color.LightGray)
                .add("p+x18", "i32", Color.LightGray)
                .add("p+x1C", "i32", Color.LightGray)
                .add("p+x20", "i32", Color.LightGray)
                .add("p+x24", "i32", Color.LightGray)
                .add("p+x28", "i32", Color.LightGray)
                .add("p+x2C", "i32", Color.LightGray)
                .add("p+x30", "i32", Color.LightGray)
                .add("p+x34", "i32", Color.LightGray)
            ElseIf name = "objects9" Then
                .add("Name Offset", "i32", Color.White)
                .add("Type", "i32", Color.White)
                .add("Index", "i32", Color.White)
                .add("Model", "i32", Color.White)
                .add("Sib Offset", "i32", Color.White)
                .add("X pos", "f32", Color.White)
                .add("Y pos", "f32", Color.White)
                .add("Z pos", "f32", Color.White)
                .add("Rot X", "f32", Color.White)
                .add("Rot Y", "f32", Color.White)
                .add("Rot Z", "f32", Color.White)
                .add("Scale X", "f32", Color.White)
                .add("Scale Y", "f32", Color.White)
                .add("Scale Z", "f32", Color.White)
                .add("x38", "i32", Color.LightGray)
                .add("x3C", "i32", Color.LightGray)
                .add("x40", "i32", Color.LightGray)
                .add("x44", "i32", Color.LightGray)
                .add("x48", "i32", Color.LightGray)
                .add("x4C", "i32", Color.LightGray)
                .add("x50", "i32", Color.LightGray)
                .add("x54", "i32", Color.LightGray)
                .add("x58", "i32", Color.LightGray)
                .add("x5C", "i32", Color.LightGray)
                .add("x60", "i32", Color.LightGray)
                .setNameIndex(.fieldCount)
                .add("Name", "string", Color.White)
                .add("Sibpath", "string", Color.White)
                .add("EventEntityID", "i32", Color.White)
                .add("p+x04", "i8", Color.LightGray)
                .add("p+x05", "i8", Color.LightGray)
                .add("p+x06", "i8", Color.LightGray)
                .add("p+x07", "i8", Color.LightGray)
                .add("p+x08", "i32", Color.LightGray)
                .add("p+x0C", "i8", Color.LightGray)
                .add("p+x0D", "i8", Color.LightGray)
                .add("p+x0E", "i8", Color.LightGray)
                .add("p+x0F", "i8", Color.LightGray)
                .add("p+x10", "i8", Color.LightGray)
                .add("p+x11", "i8", Color.LightGray)
                .add("p+x12", "i8", Color.LightGray)
                .add("p+x13", "i8", Color.LightGray)
                .add("p+x14", "i32", Color.LightGray)
                .add("p+x18", "i32", Color.LightGray)
                .add("PhysIndex", "i32", Color.White)
                .add("p+x20", "i32", Color.LightGray)
                .add("p+x24", "i32", Color.LightGray)
                .add("p+x28", "i32", Color.LightGray)
                .add("p+x2C", "i32", Color.LightGray)
            ElseIf name = "creatures10" Then
                .add("Name Offset", "i32", Color.White)
                .add("Type", "i32", Color.White)
                .add("Index", "i32", Color.White)
                .add("Model", "i32", Color.White)
                .add("Sib Offset", "i32", Color.White)
                .add("X pos", "f32", Color.White)
                .add("Y pos", "f32", Color.White)
                .add("Z pos", "f32", Color.White)
                .add("Rot X", "f32", Color.White)
                .add("Rot Y", "f32", Color.White)
                .add("Rot Z", "f32", Color.White)
                .add("Scale X", "f32", Color.White)
                .add("Scale Y", "f32", Color.White)
                .add("Scale Z", "f32", Color.White)
                .add("x38", "i32", Color.LightGray)
                .add("x3C", "i32", Color.LightGray)
                .add("x40", "i32", Color.LightGray)
                .add("x44", "i32", Color.LightGray)
                .add("x48", "i32", Color.LightGray)
                .add("x4C", "i32", Color.LightGray)
                .add("x50", "i32", Color.LightGray)
                .add("x54", "i32", Color.LightGray)
                .add("x58", "i32", Color.LightGray)
                .add("x5C", "i32", Color.LightGray)
                .add("x60", "i32", Color.LightGray)
                .setNameIndex(.fieldCount)
                .add("Name", "string", Color.White)
                .add("Sibpath", "string", Color.White)
                .add("EventEntityID", "i32", Color.White)
                .add("LightId", "i8", Color.White)
                .add("FogId", "i8", Color.White)
                .add("ScatId", "i8", Color.White)
                .add("p+x07", "i8", Color.LightGray)
                .add("p+x08", "i32", Color.LightGray)
                .add("p+x0C", "i32", Color.LightGray)
                .add("p+x10", "i32", Color.LightGray)
                .add("p+x14", "i32", Color.LightGray)
                .add("p+x18", "i32", Color.LightGray)
                .add("p+x1C", "i32", Color.LightGray)
                .add("p+x20", "i32", Color.LightGray)
                .add("NPC ID", "i32", Color.White)
                .add("p+x28", "i32", Color.LightGray)
                .add("p+x2C", "i32", Color.LightGray)
                .add("p+x30", "i32", Color.LightGray)
                .add("PhysIndex", "i32", Color.White)
                .add("p+x38", "i32", Color.LightGray)
                .add("p+x3C", "i32", Color.LightGray)
                .add("p+x40", "i32", Color.LightGray)
                .add("p+x44", "i32", Color.LightGray)
                .add("p+x48", "i32", Color.LightGray)
                .add("p+x4C", "i32", Color.LightGray)
                .add("AnimID", "i32", Color.White)
                .add("p+x54", "i32", Color.LightGray)
            ElseIf name = "collision11" Then
                .add("Name Offset", "i32", Color.White)
                .add("Type", "i32", Color.White)
                .add("Index", "i32", Color.White)
                .add("Model", "i32", Color.White)
                .add("Sib Offset", "i32", Color.White)
                .add("X pos", "f32", Color.White)
                .add("Y pos", "f32", Color.White)
                .add("Z pos", "f32", Color.White)
                .add("Rot X", "f32", Color.White)
                .add("Rot Y", "f32", Color.White)
                .add("Rot Z", "f32", Color.White)
                .add("Scale X", "f32", Color.White)
                .add("Scale Y", "f32", Color.White)
                .add("Scale Z", "f32", Color.White)
                .add("x38", "i32", Color.LightGray)
                .add("x3C", "i32", Color.LightGray)
                .add("x40", "i32", Color.LightGray)
                .add("x44", "i32", Color.LightGray)
                .add("x48", "i32", Color.LightGray)
                .add("x4C", "i32", Color.LightGray)
                .add("x50", "i32", Color.LightGray)
                .add("x54", "i32", Color.LightGray)
                .add("x58", "i32", Color.LightGray)
                .add("x5C", "i32", Color.LightGray)
                .add("x60", "i32", Color.LightGray)
                .setNameIndex(.fieldCount)
                .add("Name", "string", Color.White)
                .add("Sibpath", "string", Color.White)
                .add("EventEntityID", "i32", Color.White)
                .add("p+x04", "i8", Color.LightGray)
                .add("p+x05", "i8", Color.LightGray)
                .add("p+x06", "i8", Color.LightGray)
                .add("p+x07", "i8", Color.LightGray)
                .add("p+x08", "i8", Color.LightGray)
                .add("p+x09", "i8", Color.LightGray)
                .add("p+x0A", "i8", Color.LightGray)
                .add("p+x0B", "i8", Color.LightGray)
                .add("p+x0C", "i8", Color.LightGray)
                .add("p+x0D", "i8", Color.LightGray)
                .add("p+x0E", "i8", Color.LightGray)
                .add("p+x0F", "i8", Color.LightGray)
                .add("p+x10", "i8", Color.LightGray)
                .add("p+x11", "i8", Color.LightGray)
                .add("p+x12", "i8", Color.LightGray)
                .add("p+x13", "i8", Color.LightGray)
                .add("p+x14", "i8", Color.LightGray)
                .add("p+x15", "i8", Color.LightGray)
                .add("p+x16", "i8", Color.LightGray)
                .add("p+x17", "i8", Color.LightGray)
                .add("p+x18", "i8", Color.LightGray)
                .add("p+x19", "i8", Color.LightGray)
                .add("p+x1A", "i8", Color.LightGray)
                .add("p+x1B", "i8", Color.LightGray)
                .add("p+x1C", "i16", Color.LightGray)
                .add("p+x1E", "i16", Color.LightGray)
                .add("p+x20", "i32", Color.LightGray)
                .add("p+x24", "i32", Color.LightGray)
            Else
                Throw New Exception()
            End If
        End With

        Return layout
    End Function
End Class
